from __future__ import annotations

from collections import Counter
from pathlib import Path
from typing import Any

from .anvil import RegionFile, decode_indices, inspect_chunk, local_index, palette_index_to_block, region_coords, summarize_chunk_palette
from .anvil import load_chunk_with_cache
from .compat import detect_world_info
from .config import ServerConfig
from .paths import world_dimension_path
from .preview import render_map_preview, render_slice_preview
from .safety import begin_write
from .world_ops import scan_world_coverage
from .worldgen import list_generation_interfaces, worldgen_report

try:
    from . import _preview_accel as _PREVIEW_ACCEL
except Exception:
    _PREVIEW_ACCEL = None

AIR_OR_WATER = {"minecraft:air", "minecraft:cave_air", "minecraft:void_air", "minecraft:water"}
BASELINE_WORLD_BLOCKS = AIR_OR_WATER | {
    "minecraft:bedrock",
    "minecraft:sand",
    "minecraft:sandstone",
    "minecraft:stone",
    "minecraft:deepslate",
    "minecraft:dirt",
    "minecraft:gravel",
}
MAX_SIMULATION_CHUNKS = 256
MAX_PALETTE_SAMPLE_CHUNKS = 64
MAX_CHUNK_DETAIL_SAMPLES = 16
SIMULATION_MIN_Y = -64
SIMULATION_MAX_Y = 96

def list_local_worlds(config: ServerConfig) -> list[dict[str, Any]]:
    worlds: list[dict[str, Any]] = []
    for path in sorted(config.root.iterdir(), key=lambda item: item.name.lower()):
        if not path.is_dir() or not (path / "level.dat").exists():
            continue
        world_config = ServerConfig(config.root, path.name)
        info = detect_world_info(world_config).as_dict()
        worlds.append({
            "name": path.name,
            "path": path.relative_to(config.root).as_posix(),
            "active": path.resolve() == config.world.resolve(),
            "datapacks": len(list((path / "datapacks").iterdir())) if (path / "datapacks").exists() else 0,
            "dimensions": _dimension_counts(world_config),
            "platform": info["platform"],
            "data_version": info["data_version"],
            "support_level": info["support_level"],
        })
    return worlds


def worldgen_source_plan(config: ServerConfig, source_world_name: str = "") -> dict[str, Any]:
    source_name = source_world_name or f"{config.world_name}_regen_source"
    source_config = _world_config(config, source_name)
    source_exists = source_config.world.exists()
    return {
        "goal": "Use Minecraft/Arclight to execute datapack, mod, and plugin worldgen, then use this MCP only for offline inspection and chunk transfer.",
        "active_world": config.world_name,
        "recommended_source_world": source_name,
        "source_exists": source_exists,
        "source_path": str(source_config.world),
        "can_execute_worldgen": False,
        "why": "This MCP edits Anvil/NBT/datapack files offline. It does not run Minecraft's chunk generator, jigsaw placement, biome modifiers, mod worldgen code, or plugin worldgen code.",
        "workflow": [
            f"Set server.properties level-name={source_name}, or create that world by your normal server workflow.",
            "Start Arclight/Minecraft with the same datapacks, mods, and plugins, then generate or pregenerate the needed chunks.",
            "Stop the server completely.",
            "Use simulate_worldgen_generation to treat the server-generated source world as a worldgen simulation sample.",
            "Use compare_world_chunks to confirm which source chunks exist and which target chunks would be overwritten.",
            "Use import_chunks_from_world to copy generated region/entities/poi chunk records into the active target world.",
            "Use render_map_preview, inspect_chunk, list_entities, list_poi, and worldgen_report for offline verification.",
        ],
        "source_summary": _world_summary(source_config) if source_exists else None,
    }


def simulate_worldgen_generation(
    config: ServerConfig,
    source_world_name: str = "",
    min_cx: int = -1,
    min_cz: int = -1,
    max_cx: int = 1,
    max_cz: int = 1,
    dimension: str = "overworld",
    sample: int = 1,
    include_previews: bool = True,
    confirm: bool = False,
) -> dict[str, Any]:
    """Inspect a server-generated source world as the simulation result for worldgen.

    The MCP still does not run Minecraft's generator. This tool lets assistants
    use a local source world that was generated by the real server as a compact
    "simulation sample": chunk presence, palette signals, seafloor shape, and
    preview images are returned in one report.
    """
    source_name = source_world_name or f"{config.world_name}_regen_source"
    source_config = _world_config(config, source_name)
    min_cx, max_cx = sorted((int(min_cx), int(max_cx)))
    min_cz, max_cz = sorted((int(min_cz), int(max_cz)))
    sample = _normalize_sample(sample)
    requested_chunks = (max_cx - min_cx + 1) * (max_cz - min_cz + 1)
    if requested_chunks > MAX_SIMULATION_CHUNKS and not confirm:
        raise ValueError(f"large worldgen simulation requires confirm=true above {MAX_SIMULATION_CHUNKS} chunks")

    base = {
        "simulation_type": "server_generated_source_world",
        "server_mechanism": {
            "uses_real_minecraft_worldgen": True,
            "can_execute_worldgen_inside_mcp": False,
            "description": (
                "Run Minecraft/Arclight with the source world selected, let it generate chunks, "
                "then stop the server. This MCP inspects those generated Anvil files offline."
            ),
        },
        "accelerator": _accelerator_summary(),
        "active_world": config.world_name,
        "source_world": source_name,
        "source_path": str(source_config.world),
        "dimension": dimension,
        "requested": {
            "min_cx": min_cx,
            "min_cz": min_cz,
            "max_cx": max_cx,
            "max_cz": max_cz,
            "chunks": requested_chunks,
        },
    }
    if not source_config.world.exists():
        return {
            **base,
            "ok": False,
            "success": False,
            "complete_requested_area": False,
            "generated_chunks": 0,
            "missing_chunks": [{"cx": cx, "cz": cz} for cx in range(min_cx, max_cx + 1) for cz in range(min_cz, max_cz + 1)][:200],
            "diagnosis": "Source world does not exist yet; run the server once with this level-name or create it through your normal workflow.",
            "next_steps": [
                f"Set server.properties level-name={source_name}, or otherwise create that source world.",
                "Start Minecraft/Arclight with the same datapacks, mods, and plugins, generate the requested chunks, then stop the server.",
                "Run simulate_worldgen_generation again against the generated source world.",
            ],
        }

    presence = _chunk_presence(source_config, min_cx, min_cz, max_cx, max_cz, dimension)
    present_chunks = presence["present_chunks"]
    missing_chunks = presence["missing_chunks"]
    palette_report = _palette_report(source_config, present_chunks, dimension)
    appearance = _appearance_summary(source_config, present_chunks, min_cx, min_cz, max_cx, max_cz, dimension, sample)
    previews = _simulation_previews(source_config, min_cx, min_cz, max_cx, max_cz, dimension, sample) if include_previews else {}
    resource_report = _safe_worldgen_report(source_config)
    generation_interfaces = _safe_generation_interfaces(source_config)
    signal = _generation_signal(palette_report["palette_counts"], appearance)
    success = bool(present_chunks)
    complete = len(present_chunks) == requested_chunks

    return {
        **base,
        "ok": success,
        "success": success,
        "complete_requested_area": complete,
        "generated_chunks": len(present_chunks),
        "missing_chunks": missing_chunks[:200],
        "truncated_missing_chunks": len(missing_chunks) > 200,
        "support": detect_world_info(source_config).as_dict(),
        "coverage": scan_world_coverage(source_config, dimension),
        "generation_interfaces": generation_interfaces,
        "worldgen_resources": resource_report,
        "appearance": {
            **appearance,
            "dominant_blocks": _top_counts(palette_report["palette_counts"], 20),
            "notable_blocks": _top_counts(palette_report["notable_blocks"], 20),
            "palette_chunks_sampled": palette_report["chunks_sampled"],
            "chunk_samples": palette_report["chunk_samples"],
        },
        "generation_signal": signal,
        "previews": previews,
        "diagnosis": _simulation_diagnosis(success, complete, signal, missing_chunks),
        "next_steps": _simulation_next_steps(success, complete, source_name),
    }


def compare_world_chunks(
    config: ServerConfig,
    source_world_name: str,
    min_cx: int,
    min_cz: int,
    max_cx: int,
    max_cz: int,
    dimension: str = "overworld",
) -> dict[str, Any]:
    source_config = _world_config(config, source_world_name)
    _assert_source_not_target(config, source_config)
    min_cx, max_cx = sorted((min_cx, max_cx))
    min_cz, max_cz = sorted((min_cz, max_cz))
    source_regions: dict[Path, RegionFile] = {}
    target_regions: dict[Path, RegionFile] = {}
    source_present: list[dict[str, int]] = []
    target_present: list[dict[str, int]] = []
    missing_source: list[dict[str, int]] = []
    for cx in range(min_cx, max_cx + 1):
        for cz in range(min_cz, max_cz + 1):
            src_path, src_index = _chunk_region_path(source_config, dimension, "region", cx, cz)
            dst_path, dst_index = _chunk_region_path(config, dimension, "region", cx, cz)
            src_region = source_regions.setdefault(src_path, RegionFile(src_path))
            dst_region = target_regions.setdefault(dst_path, RegionFile(dst_path))
            chunk = {"cx": cx, "cz": cz}
            if src_region.get_raw(src_index) is None:
                missing_source.append(chunk)
            else:
                source_present.append(chunk)
            if dst_region.get_raw(dst_index) is not None:
                target_present.append(chunk)
    total = (max_cx - min_cx + 1) * (max_cz - min_cz + 1)
    return {
        "source_world": source_world_name,
        "target_world": config.world_name,
        "dimension": dimension,
        "requested": {"min_cx": min_cx, "min_cz": min_cz, "max_cx": max_cx, "max_cz": max_cz, "chunks": total},
        "source_present": len(source_present),
        "target_present": len(target_present),
        "missing_source": missing_source[:200],
        "would_import": source_present[:200],
        "truncated_lists": len(missing_source) > 200 or len(source_present) > 200,
    }


def import_chunks_from_world(
    config: ServerConfig,
    source_world_name: str,
    chunks: list[dict[str, int]],
    dimension: str = "overworld",
    include_entities: bool = True,
    include_poi: bool = True,
    confirm: bool = False,
) -> dict[str, Any]:
    if not confirm:
        raise ValueError("chunk import requires confirm=true")
    if not chunks:
        return {"ok": True, "imported_region_chunks": 0, "imported_entity_chunks": 0, "imported_poi_chunks": 0}
    source_config = _world_config(config, source_world_name)
    _assert_source_not_target(config, source_config)
    _assert_import_supported(source_config)
    roots = ["region"]
    if include_entities:
        roots.append("entities")
    if include_poi:
        roots.append("poi")

    target_files: set[Path] = set()
    imports: list[tuple[str, Path, Path, int, bytes]] = []
    missing: list[dict[str, Any]] = []
    for item in chunks:
        cx, cz = int(item["cx"]), int(item["cz"])
        for root_name in roots:
            src_path, index = _chunk_region_path(source_config, dimension, root_name, cx, cz)
            dst_path, _ = _chunk_region_path(config, dimension, root_name, cx, cz)
            raw = RegionFile(src_path).get_raw(index)
            if raw is None:
                if root_name == "region":
                    missing.append({"cx": cx, "cz": cz, "type": root_name, "source": str(src_path)})
                continue
            target_files.add(dst_path)
            imports.append((root_name, src_path, dst_path, index, raw))

    if missing:
        raise FileNotFoundError(f"source world is missing required terrain chunks: {missing[:20]}")

    backup = begin_write(config, f"import_chunks_from_world {source_world_name} {dimension}", sorted(target_files))
    target_regions: dict[Path, RegionFile] = {}
    counts = {"region": 0, "entities": 0, "poi": 0}
    source_files: set[str] = set()
    for root_name, src_path, dst_path, index, raw in imports:
        target_region = target_regions.setdefault(dst_path, RegionFile(dst_path))
        target_region.set_raw(index, raw)
        counts[root_name] += 1
        source_files.add(src_path.relative_to(config.root).as_posix())
    for region in target_regions.values():
        region.write()
    backup.write_manifest()
    return {
        "ok": True,
        "source_world": source_world_name,
        "target_world": config.world_name,
        "dimension": dimension,
        "requested_chunks": len(chunks),
        "imported_region_chunks": counts["region"],
        "imported_entity_chunks": counts["entities"],
        "imported_poi_chunks": counts["poi"],
        "source_files": sorted(source_files),
        "target_files": sorted(path.relative_to(config.root).as_posix() for path in target_files),
        "backup": str(backup.root),
    }


def _chunk_presence(
    config: ServerConfig,
    min_cx: int,
    min_cz: int,
    max_cx: int,
    max_cz: int,
    dimension: str,
) -> dict[str, list[dict[str, int]]]:
    regions: dict[Path, RegionFile] = {}
    present: list[dict[str, int]] = []
    missing: list[dict[str, int]] = []
    for cx in range(min_cx, max_cx + 1):
        for cz in range(min_cz, max_cz + 1):
            path, index = _chunk_region_path(config, dimension, "region", cx, cz)
            region = regions.setdefault(path, RegionFile(path))
            chunk = {"cx": cx, "cz": cz}
            if region.get_raw(index) is None:
                missing.append(chunk)
            else:
                present.append(chunk)
    return {"present_chunks": present, "missing_chunks": missing}


def _palette_report(config: ServerConfig, chunks: list[dict[str, int]], dimension: str) -> dict[str, Any]:
    palette_counts: Counter[str] = Counter()
    notable_blocks: Counter[str] = Counter()
    samples: list[dict[str, Any]] = []
    sampled_chunks = chunks[:MAX_PALETTE_SAMPLE_CHUNKS]
    for ordinal, item in enumerate(sampled_chunks):
        cx, cz = int(item["cx"]), int(item["cz"])
        try:
            palette = summarize_chunk_palette(config, cx, cz, dimension)
            chunk_counts = Counter({str(block): int(count) for block, count in palette["palette_counts"].items()})
            palette_counts.update(chunk_counts)
            notable = Counter({
                block: count
                for block, count in chunk_counts.items()
                if _base_block_id(block) not in BASELINE_WORLD_BLOCKS
            })
            notable_blocks.update(notable)
            if ordinal < MAX_CHUNK_DETAIL_SAMPLES:
                samples.append({
                    **inspect_chunk(config, cx, cz, dimension),
                    "dominant_blocks": _top_counts(chunk_counts, 10),
                    "notable_blocks": _top_counts(notable, 10),
                })
        except Exception as exc:
            if ordinal < MAX_CHUNK_DETAIL_SAMPLES:
                samples.append({"cx": cx, "cz": cz, "error": str(exc)})
    return {
        "palette_counts": palette_counts,
        "notable_blocks": notable_blocks,
        "chunks_sampled": len(sampled_chunks),
        "chunk_samples": samples,
    }


def _appearance_summary(
    config: ServerConfig,
    chunks: list[dict[str, int]],
    min_cx: int,
    min_cz: int,
    max_cx: int,
    max_cz: int,
    dimension: str,
    sample: int,
) -> dict[str, Any]:
    if not chunks:
        return {
            "columns_sampled": 0,
            "ocean_floor_y": None,
            "shape": "no_generated_chunks",
        }
    present = {(int(item["cx"]), int(item["cz"])) for item in chunks}
    regions: dict[Path, RegionFile] = {}
    loaded: dict[tuple[int, int], tuple[Path, RegionFile, int, Any]] = {}
    columns_by_chunk: dict[tuple[int, int], list[int]] = {}
    heights: Counter[int] = Counter()
    floor_blocks: Counter[str] = Counter()
    missing_columns = 0
    x1, x2 = min_cx * 16, max_cx * 16 + 15
    z1, z2 = min_cz * 16, max_cz * 16 + 15
    for z in range(z1, z2 + 1, sample):
        for x in range(x1, x2 + 1, sample):
            cx, cz = x >> 4, z >> 4
            if (cx, cz) not in present:
                missing_columns += 1
                continue
            columns_by_chunk.setdefault((cx, cz), []).append(((z & 15) << 4) | (x & 15))

    for (cx, cz), columns in columns_by_chunk.items():
        try:
            loaded[(cx, cz)] = loaded.get((cx, cz)) or load_chunk_with_cache(config, cx, cz, dimension, regions)
        except FileNotFoundError:
            missing_columns += len(columns)
            continue
        chunk = loaded[(cx, cz)][3]
        for column, height, block in _floor_projection_from_chunk(chunk, columns):
            if height is None:
                missing_columns += 1
            else:
                heights[height] += 1
                floor_blocks[block] += 1
    if not heights:
        return {
            "columns_sampled": missing_columns,
            "missing_columns": missing_columns,
            "ocean_floor_y": None,
            "shape": "no_solid_floor_found",
        }
    min_y, max_y = min(heights), max(heights)
    span = max_y - min_y
    if span >= 4:
        shape = "varied_terrain_or_structures"
    elif span > 0:
        shape = "slightly_varied_floor"
    else:
        shape = "flat_floor_in_sample"
    return {
        "columns_sampled": sum(heights.values()) + missing_columns,
        "missing_columns": missing_columns,
        "ocean_floor_y": {
            "min": min_y,
            "max": max_y,
            "span": span,
            "common": [{"y": y, "count": count} for y, count in heights.most_common(12)],
        },
        "floor_blocks": _top_counts(floor_blocks, 20),
        "shape": shape,
    }


def _simulation_previews(
    config: ServerConfig,
    min_cx: int,
    min_cz: int,
    max_cx: int,
    max_cz: int,
    dimension: str,
    sample: int,
) -> dict[str, Any]:
    x1, x2 = min_cx * 16, max_cx * 16 + 15
    z1, z2 = min_cz * 16, max_cz * 16 + 15
    center_x = (x1 + x2) // 2
    previews: dict[str, Any] = {}
    preview_jobs = [
        ("surface", lambda: render_map_preview(config, x1, z1, x2, z2, "surface", dimension, sample)),
        ("ocean_floor", lambda: render_map_preview(config, x1, z1, x2, z2, "ocean_floor", dimension, sample)),
        ("slice_x", lambda: render_slice_preview(config, "x", center_x, z1, z2, SIMULATION_MIN_Y, SIMULATION_MAX_Y, dimension)),
    ]
    for name, render in preview_jobs:
        try:
            previews[name] = render()
        except Exception as exc:
            previews[name] = {"ok": False, "error": str(exc)}
    return previews


def _safe_worldgen_report(config: ServerConfig) -> dict[str, Any]:
    if not (config.world / "datapacks").exists():
        return {
            "datapacks_dir_exists": False,
            "summary": "Source world has no datapacks directory; resource validation was skipped.",
        }
    try:
        return worldgen_report(config)
    except Exception as exc:
        return {"error": str(exc)}


def _safe_generation_interfaces(config: ServerConfig) -> dict[str, Any]:
    try:
        return list_generation_interfaces(config)
    except Exception as exc:
        return {"error": str(exc)}


def _generation_signal(palette_counts: Counter[str], appearance: dict[str, Any]) -> dict[str, Any]:
    notable_total = sum(
        count
        for block, count in palette_counts.items()
        if _base_block_id(block) not in BASELINE_WORLD_BLOCKS
    )
    floor = appearance.get("ocean_floor_y") or {}
    floor_span = int(floor.get("span", 0)) if isinstance(floor, dict) else 0
    if notable_total and floor_span:
        strength = "strong"
        reason = "sample contains non-baseline worldgen blocks and varied floor height"
    elif notable_total:
        strength = "medium"
        reason = "sample contains non-baseline worldgen blocks"
    elif floor_span:
        strength = "medium"
        reason = "sample contains varied terrain height"
    else:
        strength = "chunks_only"
        reason = "chunks exist, but sampled blocks look like baseline terrain"
    return {
        "strength": strength,
        "reason": reason,
        "notable_block_volume": notable_total,
        "floor_height_span": floor_span,
    }


def _simulation_diagnosis(
    success: bool,
    complete: bool,
    signal: dict[str, Any],
    missing_chunks: list[dict[str, int]],
) -> str:
    if not success:
        return "No generated chunks were found in the requested source-world area."
    if not complete:
        return f"Partial server-generation sample found; {len(missing_chunks)} requested chunks are still missing."
    if signal["strength"] == "chunks_only":
        return "Requested chunks exist, but the sampled appearance is close to baseline terrain; use a larger area or inspect structure placement if a feature should appear here."
    return "Requested chunks exist and the sampled appearance contains worldgen signals."


def _simulation_next_steps(success: bool, complete: bool, source_name: str) -> list[str]:
    if not success:
        return [
            f"Run the server with level-name={source_name} and generate the requested chunk area.",
            "Stop the server before using write/import tools.",
        ]
    if not complete:
        return [
            "Generate or pregenerate the missing chunk coordinates in the source world.",
            "Run simulate_worldgen_generation again to refresh the sample.",
        ]
    return [
        "Open the preview PNGs to inspect the generated shape.",
        "Use compare_world_chunks before importing the source chunks into the target world.",
    ]


def _floor_projection_from_chunk(chunk: Any, columns: list[int]) -> list[tuple[int, int | None, str]]:
    unresolved = list(dict.fromkeys(columns))
    blocks = ["minecraft:air"] * 256
    heights: list[int | None] = [None] * 256
    sections = []
    for section in chunk.get("sections", []):
        block_states = section.get("block_states")
        if not block_states:
            continue
        palette = block_states.get("palette", [])
        if not palette:
            continue
        palette_blocks = [palette_index_to_block(section, index) for index in range(len(palette))]
        sections.append((
            int(section.get("Y", 0)),
            block_states,
            palette_blocks,
            [_base_block_id(block) for block in palette_blocks],
        ))
    sections.sort(key=lambda item: item[0], reverse=True)
    for section_y, block_states, palette_blocks, palette_base_names in sections:
        if not unresolved:
            break
        if section_y * 16 > SIMULATION_MAX_Y or section_y * 16 + 15 < SIMULATION_MIN_Y:
            continue
        indices = _decode_indices_fast(block_states)
        unresolved = _fill_floor_projection(
            indices,
            palette_blocks,
            palette_base_names,
            AIR_OR_WATER,
            unresolved,
            blocks,
            heights,
            section_y,
            SIMULATION_MIN_Y,
            SIMULATION_MAX_Y,
        )
    return [(column, heights[column], blocks[column]) for column in columns]


def _decode_indices_fast(block_states: Any) -> list[int]:
    if _PREVIEW_ACCEL is not None and hasattr(_PREVIEW_ACCEL, "decode_indices"):
        return _PREVIEW_ACCEL.decode_indices(block_states.get("data"), len(block_states["palette"]))
    return decode_indices(block_states)


def _fill_floor_projection(
    indices: list[int],
    palette: list[str],
    palette_base_names: list[str],
    skip: set[str],
    unresolved: list[int],
    blocks: list[str],
    heights: list[int | None],
    section_y: int,
    min_y: int,
    max_y: int,
) -> list[int]:
    if _PREVIEW_ACCEL is not None and hasattr(_PREVIEW_ACCEL, "fill_floor_projection"):
        return _PREVIEW_ACCEL.fill_floor_projection(indices, palette, palette_base_names, skip, unresolved, blocks, heights, section_y, min_y, max_y)

    remaining = unresolved
    palette_len = len(palette)
    for ly in range(15, -1, -1):
        next_remaining: list[int] = []
        y = section_y * 16 + ly
        if y > max_y:
            continue
        if y < min_y:
            break
        y_offset = ly << 8
        for column in remaining:
            palette_index = indices[y_offset | column]
            if 0 <= palette_index < palette_len:
                block = palette[palette_index]
                base_name = palette_base_names[palette_index]
            else:
                block = "minecraft:air"
                base_name = "minecraft:air"
            if base_name in skip:
                next_remaining.append(column)
            else:
                blocks[column] = block
                heights[column] = y
        remaining = next_remaining
        if not remaining:
            break
    return remaining


def _accelerator_summary() -> dict[str, Any]:
    return {
        "cython_module_available": _PREVIEW_ACCEL is not None,
        "decode_indices": _PREVIEW_ACCEL is not None and hasattr(_PREVIEW_ACCEL, "decode_indices"),
        "floor_projection": _PREVIEW_ACCEL is not None and hasattr(_PREVIEW_ACCEL, "fill_floor_projection"),
    }


def _block_from_chunk(chunk: Any, x: int, y: int, z: int) -> str:
    section_y = y // 16
    for section in chunk.get("sections", []):
        if int(section.get("Y", 999999)) != section_y:
            continue
        block_states = section.get("block_states")
        if not block_states:
            return "minecraft:air"
        palette = block_states.get("palette", [])
        if not palette:
            return "minecraft:air"
        indices = decode_indices(block_states)
        index = indices[local_index(x, y, z)]
        return palette_index_to_block(section, index)
    return "minecraft:air"


def _base_block_id(block: str) -> str:
    return block.split("[", 1)[0]


def _normalize_sample(sample: int) -> int:
    try:
        value = int(sample)
    except (TypeError, ValueError):
        raise ValueError("sample must be a positive integer") from None
    if value < 1:
        raise ValueError("sample must be a positive integer")
    return value


def _top_counts(counts: Counter[str], limit: int) -> list[dict[str, Any]]:
    return [
        {"block": block, "count": count}
        for block, count in sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:limit]
    ]


def _world_config(config: ServerConfig, world_name: str) -> ServerConfig:
    if not world_name or Path(world_name).name != world_name or world_name in (".", ".."):
        raise ValueError("world_name must be a local world directory name under MC_SERVER_ROOT")
    world = (config.root / world_name).resolve()
    world.relative_to(config.root.resolve())
    return ServerConfig(config.root, world_name)


def _assert_source_not_target(config: ServerConfig, source_config: ServerConfig) -> None:
    if source_config.world.resolve() == config.world.resolve():
        raise ValueError("source world must be different from the active target world")
    if not source_config.world.exists():
        raise FileNotFoundError(f"source world does not exist: {source_config.world}")


def _assert_import_supported(source_config: ServerConfig) -> None:
    info = detect_world_info(source_config)
    if info.support_level != "full_1_20_1":
        raise RuntimeError(
            "refusing source chunk import: "
            f"source world {source_config.world_name} has platform={info.platform}, "
            f"data_version={info.data_version}, support_level={info.support_level}. {info.reason}"
        )


def _dimension_counts(config: ServerConfig) -> list[dict[str, Any]]:
    return [
        {
            "dimension": item["dimension"],
            "exists": item["exists"],
            "region_files": item["region_files"],
            "entity_files": item["entity_files"],
            "poi_files": item["poi_files"],
        }
        for item in _list_dimension_roots(config)
    ]


def _list_dimension_roots(config: ServerConfig) -> list[dict[str, Any]]:
    candidates = [
        ("overworld", config.world),
        ("nether", config.world / "DIM-1"),
        ("end", config.world / "DIM1"),
    ]
    return [
        {
            "dimension": name,
            "exists": path.exists(),
            "region_files": len(list((path / "region").glob("*.mca"))) if (path / "region").exists() else 0,
            "entity_files": len(list((path / "entities").glob("*.mca"))) if (path / "entities").exists() else 0,
            "poi_files": len(list((path / "poi").glob("*.mca"))) if (path / "poi").exists() else 0,
        }
        for name, path in candidates
    ]


def _world_summary(config: ServerConfig) -> dict[str, Any]:
    info = detect_world_info(config).as_dict()
    return {
        "world": config.world_name,
        "platform": info["platform"],
        "data_version": info["data_version"],
        "support_level": info["support_level"],
        "coverage": scan_world_coverage(config),
    }


def _chunk_region_path(config: ServerConfig, dimension: str, root_name: str, cx: int, cz: int) -> tuple[Path, int]:
    if root_name not in {"region", "entities", "poi"}:
        raise ValueError("root_name must be region, entities, or poi")
    rx, rz, index = region_coords(cx, cz)
    root = world_dimension_path(config, dimension) / root_name
    return root / f"r.{rx}.{rz}.mca", index
